[versions]
agp = "8.7.2"
kotlin = "2.0.21"
compose-bom = "2024.09.02"
lifecycle = "2.8.6"
activityCompose = "1.9.2"
coreKtx = "1.12.0"
material3 = "1.3.0"
datastorePreferences = "1.1.1"
kotlinxSerializationJson = "1.7.3"

# Test
junit = "4.13.2"
junitExt = "1.1.5"
espressoCore = "3.5.1"
material = "1.12.0"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"

[libraries]
# Compose (sin versión: se toma de BOM)
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

# Activity Compose / Lifecycle / Core
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

# DataStore + Serialization
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }  # <— NUEVO

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android       = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }